### PR TITLE
support eslint v9

### PR DESCRIPTION
**Pull request by anajavi**
allow eslint v9 in peer dependencies.

context.getScope was removed in [eslint v9](https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/#context.getscope())

### CODE REVIEW

**Comment by pcorpet** [comment]
@cvazac can you take a look at this PR please? ESLint 8 is reaching end of life tomorrow https://eslint.org/blog/2024/09/eslint-v8-eol-version-support/

**Comment by cvazac** [comment]
I'll get to this ASAP, I'm running into an error running the tests, still
trying to figure it out.
> ConfigError: ESLint configuration in rule-tester is invalid: Config
(unnamed): Key "parserOptions": This appears to be in eslintrc format
rather than flat config format.

**Comment by cvazac** [comment]
I'll get to this ASAP, I'm running into an error running the tests, still
trying to figure it out.
```ConfigError: ESLint configuration in rule-tester is invalid: Config(unnamed): Key "parserOptions": This appears to be in eslintrc formatcrather than flat config format.```

**Comment by anajavi** [comment]
When running tests with eslint v9 and changing:
https://github.com/cvazac/eslint-plugin-react-perf/blob/35e9912004da57880939edd4a1ca202740157c66/tests/lib/utils/common.js#L15-L21

to:
```js
  var languageOptions = {
    ecmaVersion: 6,
    parserOptions: {
      ecmaFeatures: {
        jsx: true,
      },
    }
  };
```

Gets another error:
```
AssertionError [ERR_ASSERTION]: Test error must specify either a 'messageId' or 'message'.
```

Changing parserOptions to  languageOptions prevents running the tests with the old eslint. Is it alright to drop support for old eslint versions?

**Comment by anajavi** [comment]
I now fixed the tests to pass with eslint v9. Had to remove one duplicate test.

I had to also remove eslint-plugin-standard as it does not support eslint v9.

**Comment by anajavi** [comment]
I added flat configurations to this PR also.

**Comment by cvazac** [comment]
shipped as:
> eslint-plugin-react-perf@3.3.3
@anajavi thanks for contributing and for your patience!

**Pull request merged**
